apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appchat
  namespace: appchat
spec:
  interval: 5m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: appchat
      interval: 1m
      valuesFiles:
        - values.yaml
        - values-prod.yaml
